---
keys:
  - users: &users
      - &daluca age174z6svmuxzs8exhdp3hquzpstgpnwflhx7crt7jes7f0080z7fmqn9rgvt
  - hosts: &hosts
      - &artemis age1jthfmze0n88am6pc2tg9kkv99qqrwq0dqzgrnxt484qt3pnt9ess2en2gt
      - &stormwind age173lrwtphyuvfjhkjvw4xe5fy4lt2x97qcjr2eqjt46eq6q664egqfsp4v3
      - &ironforge age12jvysa4up79pasngsdqn2mjd5fczg4wtrx8d8euj3j8vr3nlye2seqmnjs

creation_rules:
  - path_regex: stormwind\.sops\.yaml$
    key_groups:
      - age:
          - *daluca
          - *stormwind
  - path_regex: artemis\.sops\.yaml$
    key_groups:
      - age:
          - *daluca
          - *artemis
  - path_regex: ironforge\.sops\.yaml$
    key_groups:
      - age:
          - *daluca
          - *ironforge
  - path_regex: \.sops\.yaml$
    key_groups:
      - age:
          - *daluca
          - *artemis
          - *stormwind
          - *ironforge
