keys:
  - users:
      - &daluca age174z6svmuxzs8exhdp3hquzpstgpnwflhx7crt7jes7f0080z7fmqn9rgvt
      - &lucas-slebos age1d60rtn66jj8mkx4quvwjn66mrqja83ux2flknqlreh09p06rkvpqnj7ygw
  - hosts:
      - &artemis age1jthfmze0n88am6pc2tg9kkv99qqrwq0dqzgrnxt484qt3pnt9ess2en2gt
      - &stormwind age173lrwtphyuvfjhkjvw4xe5fy4lt2x97qcjr2eqjt46eq6q664egqfsp4v3
      - &ironforge age16g33d2sppsukw7tekmh2d3ppf22sscwfmm0anppcrdtj9h5p7eqqrw9zg0
      - &darnassus age102lual882fvygyw47twjzl65uey33u2ps8ulcrr8g258vaafwvpqsj6hyy
      - &guiltyspark age1hlextplau7gmc4a58ak6v6gtmtczfp829r0ve24vm0309s9gucgsr7rucm
      - &unifi age1hvks9zyat7fq5cec7dys0jc400qwq3avqv58es2fptpcd7npsyuq3kv3s2
      - &RRS-A00690 age16c3hdsmh4ygkzfe0ekz0cg266jsjszn3pdrlstzkg0tpnmyy24rspr7m9k
      - &RRS-A00746 age1w3wwy6e42f3xahzz45a5qra6d73jzl66g0vghxcvz2ak9pnufvcsjgn8ma

creation_rules:
  - path_regex: lucas\.slebos\.sops\.yaml$
    key_groups:
      - age:
          - *daluca
          - *lucas-slebos
  - path_regex: stormwind\.sops\.yaml$
    key_groups:
      - age:
          - *daluca
          - *stormwind
  - path_regex: artemis\.sops\.yaml$
    key_groups:
      - age:
          - *daluca
          - *artemis
  - path_regex: ironforge\.sops\.yaml$
    key_groups:
      - age:
          - *daluca
          - *ironforge
  - path_regex: darnassus\.sops\.yaml$
    key_groups:
      - age:
          - *daluca
          - *darnassus
  - path_regex: guiltyspark\.sops\.yaml$
    key_groups:
      - age:
          - *daluca
          - *guiltyspark
  - path_regex: unifi\.sops\.yaml$
    key_groups:
      - age:
          - *daluca
          - *unifi
  - path_regex: RRS-A00690\.sops\.yaml$
    key_groups:
      - age:
          - *daluca
          - *RRS-A00690
  - path_regex: RRS-A00746\.sops\.yaml$
    key_groups:
      - age:
          - *daluca
          - *RRS-A00746
  - path_regex: \.sops\.yaml$
    key_groups:
      - age:
          - *daluca
          - *artemis
          - *stormwind
          - *ironforge
          - *darnassus
          - *guiltyspark
          - *unifi
          - *RRS-A00690
          - *RRS-A00746

stores:
  yaml:
    indent: 2
