keys:
  - users:
      - &daluca age174z6svmuxzs8exhdp3hquzpstgpnwflhx7crt7jes7f0080z7fmqn9rgvt
  - hosts:
      - &artemis age1jthfmze0n88am6pc2tg9kkv99qqrwq0dqzgrnxt484qt3pnt9ess2en2gt
      - &stormwind age173lrwtphyuvfjhkjvw4xe5fy4lt2x97qcjr2eqjt46eq6q664egqfsp4v3
      - &ironforge age16g33d2sppsukw7tekmh2d3ppf22sscwfmm0anppcrdtj9h5p7eqqrw9zg0
      - &darnassus age102lual882fvygyw47twjzl65uey33u2ps8ulcrr8g258vaafwvpqsj6hyy
      - &azeroth age1hlextplau7gmc4a58ak6v6gtmtczfp829r0ve24vm0309s9gucgsr7rucm
      - &unifi age1hvks9zyat7fq5cec7dys0jc400qwq3avqv58es2fptpcd7npsyuq3kv3s2

creation_rules:
  - path_regex: stormwind\.sops\.yaml$
    key_groups:
      - age:
          - *daluca
          - *stormwind
  - path_regex: artemis\.sops\.yaml$
    key_groups:
      - age:
          - *daluca
          - *artemis
  - path_regex: ironforge\.sops\.yaml$
    key_groups:
      - age:
          - *daluca
          - *ironforge
  - path_regex: darnassus\.sops\.yaml$
    key_groups:
      - age:
          - *daluca
          - *darnassus
  - path_regex: azeroth\.sops\.yaml$
    key_groups:
      - age:
          - *daluca
          - *azeroth
  - path_regex: unifi\.sops\.yaml$
    key_groups:
      - age:
          - *daluca
          - *unifi
  - path_regex: \.sops\.yaml$
    key_groups:
      - age:
          - *daluca
          - *artemis
          - *stormwind
          - *ironforge
          - *darnassus
          - *azeroth
          - *unifi

stores:
  yaml:
    indent: 2
