keys:
  - &master age174z6svmuxzs8exhdp3hquzpstgpnwflhx7crt7jes7f0080z7fmqn9rgvt
  - users:
      - &daluca age1t7uj9cz0dwrm555qred7n49t5c2shtuuwwsc6ryd3fewunx7x32s7rlkt0
      - &lucas-slebos age1d60rtn66jj8mkx4quvwjn66mrqja83ux2flknqlreh09p06rkvpqnj7ygw
  - hosts:
      - &artemis age1jthfmze0n88am6pc2tg9kkv99qqrwq0dqzgrnxt484qt3pnt9ess2en2gt
      - &stormwind age173lrwtphyuvfjhkjvw4xe5fy4lt2x97qcjr2eqjt46eq6q664egqfsp4v3
      - &ironforge age16g33d2sppsukw7tekmh2d3ppf22sscwfmm0anppcrdtj9h5p7eqqrw9zg0
      - &darnassus age102lual882fvygyw47twjzl65uey33u2ps8ulcrr8g258vaafwvpqsj6hyy
      - &dalaran age13n7tntegd6zw8ne0n4at2zlxz425xptlwsceu36tg7tw56f8upcssr4u8u
      - &homeassistant age1uv4kdnmu9qzmq3r7ehfmnt603kzt5ywkztlaelpvymdxawp8p9fs4vl0u4
      - &guiltyspark age1hlextplau7gmc4a58ak6v6gtmtczfp829r0ve24vm0309s9gucgsr7rucm
      - &unifi age1hvks9zyat7fq5cec7dys0jc400qwq3avqv58es2fptpcd7npsyuq3kv3s2
      - &alpha age1eyaws92hs5r7tv5elrhd8cd7axq0pa7azn5xnnxeuldv2q4l0ycsx7u3jj
      - &alfa age19fzpnfhta58lm5wduycq6j6th3x2r8d0zv9fqejh06zcllp00e8qlvlfzr
      - &bravo age182zncdt5xn9m2yjrxf0mfa5l26y0fhddzcfwvyg49t02dsmzeucsupagxs
      - &charlie age1tvw6h8psq3fz06us4ykyg0ufvh5rxv2mazlug2d32ay82lqetucszlmehu

creation_rules:
  - path_regex: daluca\.sops\.yaml$
    key_groups:
      - age:
          - *master
          - *daluca
  - path_regex: lucas\.slebos\.sops\.yaml$
    key_groups:
      - age:
          - *master
          - *lucas-slebos
  - path_regex: stormwind\.sops\.yaml$
    key_groups:
      - age:
          - *master
          - *stormwind
  - path_regex: artemis\.sops\.yaml$
    key_groups:
      - age:
          - *master
          - *artemis
  - path_regex: ironforge\.sops\.yaml$
    key_groups:
      - age:
          - *master
          - *ironforge
  - path_regex: darnassus\.sops\.yaml$
    key_groups:
      - age:
          - *master
          - *darnassus
  - path_regex: dalaran\.sops\.yaml$
    key_groups:
      - age:
          - *master
          - *dalaran
  - path_regex: homeassistant\.sops\.yaml$
    key_groups:
      - age:
          - *master
          - *homeassistant
  - path_regex: guiltyspark\.sops\.yaml$
    key_groups:
      - age:
          - *master
          - *guiltyspark
  - path_regex: unifi\.sops\.yaml$
    key_groups:
      - age:
          - *master
          - *unifi
  - path_regex: alpha\.sops\.yaml$
    key_groups:
      - age:
          - *master
          - *alpha
  - path_regex: alfa\.sops\.yaml$
    key_groups:
      - age:
          - *master
          - *alfa
  - path_regex: bravo\.sops\.yaml$
    key_groups:
      - age:
          - *master
          - *bravo
  - path_regex: charlie\.sops\.yaml$
    key_groups:
      - age:
          - *master
          - *charlie

stores:
  yaml:
    indent: 2
