---
keys:
  - &users:
    - &daluca age174z6svmuxzs8exhdp3hquzpstgpnwflhx7crt7jes7f0080z7fmqn9rgvt
  - &hosts:
    - &artemis age1jthfmze0n88am6pc2tg9kkv99qqrwq0dqzgrnxt484qt3pnt9ess2en2gt
    - &stormwind age17jkyhuxssaau5exm6m7mmtfqj7mg5h958379qs2zjkafmpdprf4qdua6mx

creation_rules:
  - path_regex: \.sops\.yaml$
    key_groups:
      - age:
        - *daluca
        - *artemis
        - *stormwind
