[default]
extend-ignore-re = [
  "(?Rm)^.*(#|//)\\s*spellchecker:disable-line$",
  "ENC\\[.*\\]",
  "sha256-.*="
]

[default.extend-words]
referers = "referers"

[files]
extend-exclude = [
  "**.asc",
  "**.sops.yaml"
]
